name: Ubuntu
env:
  APT_COMMAND: "sudo apt-get update && sudo apt-get install gcovr g++-10 clang++-11"
on: [push, pull_request]
jobs:
  build:
    name: "Build"
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        build_type: ["Debug", "Release"]
        compiler: ["g++-10", "clang++-11"]
    steps:
      # Remove apt repos that are known to break from time to time
      # See https://github.com/actions/virtual-environments/issues/323
      - name: Remove broken apt repos [Ubuntu]
        run: |
          for apt_file in `grep -lr microsoft /etc/apt/sources.list.d/`; do sudo rm $apt_file; done

      - name: Install dependencies
        run: ${{ env.APT_COMMAND }}

      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Configure
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DCMAKE_CXX_COMPILER=/usr/bin/${{ matrix.compiler }} ..
      - name: Build abacus
        run: |
          cd build
          cmake --build . --target abacus
      - name: Run abacus
        run: ./build/bin/abacus "1 + 2"

  test:
    name: "Unit tests"
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        build_type: ["Debug", "Release"]
        compiler: ["g++-10", "clang++-11"]
    steps:
      # Remove apt repos that are known to break from time to time
      # See https://github.com/actions/virtual-environments/issues/323
      - name: Remove broken apt repos [Ubuntu]
        run: |
          for apt_file in `grep -lr microsoft /etc/apt/sources.list.d/`; do sudo rm $apt_file; done
      - name: Install dependencies
        run: ${{ env.APT_COMMAND }}

      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Configure
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DCMAKE_CXX_COMPILER=/usr/bin/${{ matrix.compiler }} ..
      - name: Build tests
        run: |
          cd build
          cmake --build . --target tests
      - name: Run tests
        run: ./build/bin/tests
